### ISSUE TITLE
Quality of your RTree and CDT compared to Boost and CGAL implementations?

### ISSUE THREAD

**Issue by StefanSalewski** [Stoeoef/spade#22]
Can you tell us something about the quality of your CDT algorithm (speed and robustness) compared to CGAL lib, and maybe which papers you use to implement it?

Origin for my question is, that I would need a CDT for Nim language, and I would prefer a native implementation to restricted CGAL bindings (I made some CGAL bindings for Ruby some years ago.) Of course coding a robust and fast incremental constrained delaunay triangulation from scratch using research papers is a big task, so I am considering converting an existing implementation. Maybe from C++ or Rust. I have not yet found a nice standalone C++ implementation -- of course CGAL has one, but I guess extracting CDT code from lib is not easy. Your code is MIT licensed, same as Nim libs generally are, so it may a good candidate. I would have to learn some Rust before, but that is already on my todo list. (Funny fact is, that some weeks before I saw your spade package, I did a Nim RTree implementation myself from scratch following the original papers, see https://github.com/StefanSalewski/RTree.)

**Comment by Stoeoef** [comment]
Hey,
I haven't yet compared my library with cgal or boost, so I can't give you any performance comparisons on that end. I would be interested though, I might create one if I have the time. I'm pretty sure spade is slower than CGAL, but I can't possibly tell how much.

Regarding Robustness: Both spade and CGAL work with various geometric kernels in their background which determine the accuracy of geometric operations. Both are precise (up to _overflow issues_) when using integral coordinates, both are imprecise and can crash when using `f64` coordinates with native evaluation of predicates. However, since spade is written in safe rust, crashes will result in a incorrect results or a panic, whereas CGAL's crashes are probably undefined behaviour.
Both libraries offer precise kernels to mitigate this effect, and, as far as I've read the CGAL side, approaches differ here: CGAL uses a filtering approach as described here [1], whereas spade uses the approach described here [2] .

Spade uses a DCEL to store its triangulation, whereas CGAL represents triangulations with another format based on vertices and faces. This reduces space requirements and will probably improve performance [3].

For CDT and Delaunay Triangulations, spade uses "standard" algorithms (edge flipping and [4]). As far as I know, these algorithms are really the standard algorithms, so I expect CGAL to use them as well.

To summarize: spaded opted in for easy, working solutions, whereas CGAL as matured and feature rich project has many configurations and clever algorithms which should make it faster and more flexible. However, when translating into another language, it is very likely easier to do this from spade than from CGAL due to its smaller complexity. If performance is really important for you, I'd probably recommend to compare both libraries on an adequate test set and see how much performance difference between cgal and spade you can find. Just make sure to share your results ;) . If spade is not outperformed too badly, you're likely better of adapting this, instead of digging through the cpp code of CGAL.

[1] H. Brönnimann, C. Burnikel, and S. Pion. Interval arithmetic yields efficient dynamic filters for computational geometry. Discrete Applied Mathematics, 109:25–47, 2001.
[2] https://www.cs.cmu.edu/~quake/robust.html
[3] https://hal.inria.fr/inria-00167199/document/
[4] http://www.geom.uiuc.edu/~samuelp/del_project.html

**Comment by StefanSalewski** [comment]
Thank you very much for your detailed reply.

Speed and memory consumption is indeed not a big issue for my intended use case (http://ssalewski.de/Router.html.en) so I guess I will indeed seriously consider porting your code to Nim language. It's a good motivation for me to learn some more Rust. But I guess I will find time for that not before next winter unfortunately...

**Comment by Stoeoef** [comment]
In the meantime, other delaunay crates have been opened up - e.g. [delaunator](https://crates.io/crates/delaunator), which is not only much simpler, but also much faster than spade. It's not that feature rich, however.

I'll close this issue for now as I want to clean up spade's backlog.

**Comment by StefanSalewski** [comment]
Thank you very much for that info. I still did not found enough time to create a constrained delaunay triangulation in Nim programming language yet. But I played with the "Quad edge data structure" a bit, maybe I will prefer that one over DCEL. And I read some papers, i.e. "Fully Dynamic Constrained Delaunay Triangulations" of Kallmann and others. I will investigate your delaunator suggestsion.
