### ISSUE TITLE
What about non-Cartesian coordinates?

### ISSUE THREAD

**Issue by astrojhgu** [Stoeoef/spade#28]
I want to perform interpolation on a sphere, with (theta, phi) coordinates.

I find that if I implement PointN for a SphPoint{theta:f64, phi:f64} then the SpatialObject is automatically implemented, then the distance2 is determined. However the distance of two points on a sphere is not calculated as theta^2+phi^2, but need to first convert into (x,y,z), then calculate the inner products.

How can I properly represent a point on a sphere?

**Comment by Stoeoef** [comment]
Spade assumes all coordinates to be cartesian. Handling spherical coordinates seems to be possible in principal, but requires special handling - the current MBR implementation would need to be adjusted. However, that's currently not possible from outside.
To solve your problem I'd suggest to convert all coordinates into Cartesian R³ before inserting them into the r-tree. If backward calculation is necessary (R³ to spherical), you could implement your own point type that stores both spherical and cartesian coordinates at the same time (at the cost of additional memory).
I'm currently working on a stand alone r-tree focused package, I'll be considering other coordinate spaces for this - so thanks for the input!

**Comment by timothee-haudebourg** [comment]
Hi,

I'm also interested in working with spherical coordinates. It seems to be possible to handle such coordinate system without changing how the inner working of the data structure (theoretically). Using cartesian coordinates (using the conversion you proposed) leads to wrong results.

**Comment by timothee-haudebourg** [comment]
Here is [a paper on the subject](https://link.springer.com/chapter/10.1007%2F978-3-642-40235-7_9) (just in case).

> Databases are lacking good support for accelerated nearest neighbor queries and range queries in such datasets for the much more appropriate geodetic (great-circle) distance. In this article, we will show two approaches how a widely known spatial index structure – the R-tree – can be easily used for nearest neighbor queries with the geodetic distance, with no changes to the actual index structure.

**Comment by timothee-haudebourg** [comment]
Well, my bad, in the said paper there is a proof showing that using cartesian coordinates in this case should not lead to errors when querying the k-neighbors... So wrong results are on me.

**Comment by Stoeoef** [comment]
The rtree was moved into crate `rstar` (https://github.com/georust/rstar). Closing.

**Comment by GrantMoyer** [comment]
For anyone who finds this issue in the future, you can use spade for spherical coordinate by using a [stereographic projection][1] of the points. Since stereographic projections maps circles on the sphere to circles on the plane, the properties needed to compute the Delaunay triangulation are preserved.

Note that circles intersecting the point of projection are actually mapped to lines instead of circles. There are two ways to handle this:

- Choose a vertex as the point of projection. This vertex becomes the "point at infinity" of the outer face.
- Pick the point of projection carefully, so that it does not intersect the circumscribing circle of any delaunay triangle, otherwise these three points will become collinear. Additionally, you may need to triangulate the northern and southern hemispheres separately depending on your requirements.

[1]: https://en.wikipedia.org/wiki/Stereographic_projection
