### ISSUE TITLE
nearest_n_neighbors_iter?

### ISSUE THREAD

**Issue by brigand** [Stoeoef/spade#31]
Would it be practical to have an iterator for nearest neighbors? I have a use case where I need to get the 10 closest items to a point that pass an additional check. Best case, I need to look at 10 items, worst case, I need 25,000.

<sub>P.s. your docs are easy for a newbie to follow, thanks!</sub>

**Comment by Stoeoef** [comment]
Thanks for the proposal!
I've published v1.5.0, with a brand new `RTree::nearest_neighbor_iter(Point)` function. I was originally very hesitant about this feature as I thought it to be a nightmare to be optimized properly, however, it turned out to be surprisingly fast __in the very first implementation__ - actually, it was faster to call `nearest_neighbor_iter(..).next()` than calling the previous `nearest_neighbor(Point)`... 
Investigating the reasons for this unexpected behaviour led to some more optimizations which also found their way into v1.5.0

Great to hear that my docs are helping you :+1: !

**Comment by brigand** [comment]
Awesome! Previously I was limiting it to 5,000 locations considered, and now I can look at all of them until I find the desired number of matches. For location + string pattern matching, my best case improved by 97%!
