### ISSUE TITLE
RTree::bulk_load does not work for dimensions other than 2

### ISSUE THREAD

**Issue by varkor** [Stoeoef/spade#39]
As [per the documentation](https://docs.rs/spade/1.5.1/spade/rtree/struct.RTree.html#method.bulk_load):
> Note: The current implementation only works for two dimensional data. If other dimensions are needed, please create an issue.

In particular, I'd like to be able to bulk load 4-dimensional coördinates.

**Comment by Stoeoef** [comment]
Ugh! You got me there, I did write that down there. However, I do not plan to add new features to spade's R-Tree but will add them instead to its "replacement" crate: [rstar](https://crates.io/crates/rstar). The r-tree offered by rstar 0.2.0 supports any point dimension for bulk loading. Also, it is faster in general.

Since rstar's API was inspired by the spade implementation, the transition from spade to rstar _should_ be somewhat smooth. The main difference might be that rstar dropped the support for cgmath and nalgebra points.

I hope that solves your problem!
