### ISSUE TITLE
DelauneyTriangulation should be Sync and Send

### ISSUE THREAD

**Issue by rmanoka** [Stoeoef/spade#42]
The main datastructure for triangulation: `DelauneyTriangulation` is `!Sync`, and `!Send`.  This prevents a fairly common use-case of computing a single triangulation and then using (read-only) references from multiple threads to say interpolate values to many different points.

The issue is with the usage of `PhantomData` for storing the kernel type.  It is defined (in `delauney2d.rs` and `cdt.rs`) as:

``` rust
    __kernel: PhantomData<*const K>,
```

The issue seems to be that `*const K` is neither `Sync` nor `Send` and that propogates to the whole structure.  To the best of my understanding of the code here, we only need `K` and probably want it to be variant in `K`.  In this case, a simple `PhantomData<K>` should suffice as it should also be variant in `K`.

Would be great if you would change those two uses, so that the overall structure may be used in multi-threaded scenarios.  Nevertheless, thank you very much for this elegant implementation!

**Comment by Stoeoef** [comment]
Indeed, this is unintentional and a bug - thanks for the report!
DelaunayTriangulation was designed to be `Send` and `Sync` initially, the bug was introduced when I wanted to get rid of the drop check introduced by `PhantomData<T>` (see the [Nomicon](https://doc.rust-lang.org/nomicon/phantom-data.html)). Loosing `Send/Sync` was an oversight.

Being variant is indeed correct, either by using `PhantomData<T>` or `PhantomData<Fn() -> T>` if the nomicon can be believed.

I'll fix this in the next days, along with a few test cases that ensure that `DelaunayTriangulation` is indeed thread safe. If you want to get involved, feel free to open a PR that does that, no pressure though.

**Comment by rmanoka** [comment]
I did not realize the implication on dropck of PhantomData;  thanks for letting me know!

Happy to provide PR for the change.  I'll make the changes, and add compile-time tests to check that commonly used variants should be `Send` and `Sync`.   We could provide multi-threading test via crossbeam if you think that's worth adding to test-suite crates.
